language: minimal

services: docker

branches:
  only:
  - master
  exclude:
  - dev  # don't trigger on a dev commit

env:
  global: 
  - DOCKER_COMPOSE_VERSION=1.23.2
  - ENV_VAR='this is a practice file for Travis CI'
  - KOPS_CLUSTER_NAME=charlie.k8s.local
  - KOPS_STATE_STORE=s3://charlie-kops-state-store
  - t=240

# Run some commands.  
# ls /  (to see the full directory tree of Travis)
# ls .   (to see the contents of the present directory)
# pwd   is /home/travis/build/CharlesDoyle/practice
before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - ls /usr/local/bin/
  - curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
  - chmod +x kops-linux-amd64
  - sudo mv kops-linux-amd64 /usr/local/bin/kops
  - kops version
  - kops get clusters
  - kops validate cluster
  - kubectl config current-context
  - kops get ig
  - ls /
  - ls .
  - pwd


install:
  - echo "Hello World!"
  - sleep 10
  - echo $ENV_VAR
  - kops create cluster --node-count=1 --node-size=t2.medium --zones=us-west-2a
  - kops update cluster --name ${KOPS_CLUSTER_NAME} --yes
  - while [[ $t > 4 ]]; do sleep 30; echo 'counted 30 sec.'; t=$[t-30]; #delay
  - kubectl apply -f udagram-app.yaml