# a Travis practice file
language: minimal
# create environment variables
env: 
  - MY_CAR=Toyota

# should be a list of scripts to run before install phase
before_install:
  - echo 'before install'

# only the dev branch can be built
branches:
  only:
    - dev

install:
  - ./script1

script:
  - echo $MY_CAR
  - echo $PWD  # /home/travis/build/CharlesDoyle/practice
  - echo $PATH  # there is a PATH variable in travis
  - echo `docker -v`
  - ./file1